# Generated by Django 5.1.4 on 2025-01-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='media/placeholder_product.jpeg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stockCount',
            field=models.IntegerField(default=0),
        ),
    ]
