# Generated by Django 5.1.4 on 2025-01-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='storeuser',
            name='last_name',
        ),
    ]
