# Generated by Django 5.2.16 on 2026-07-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
