# Generated by Django 5.1.4 on 2025-01-11 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_image_alter_item_stockcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
